[package]
name = "vsedit-terminal-view"
description = "Terminal panel integration"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ratatui = { workspace = true }
vsedit-wb-terminal = { path = "../vsedit-wb-terminal" }
vsedit-terminal-plat = { path = "../vsedit-terminal-plat" }

