[package]
name = "vsedit-integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
vsedit-text-model = { path = "../vsedit-text-model" }
vsedit-editor-types = { path = "../vsedit-editor-types" }
vsedit-cursor = { path = "../vsedit-cursor" }
vsedit-editor-controller = { path = "../vsedit-editor-controller" }
vsedit-json = { path = "../vsedit-json" }
vsedit-commands = { path = "../vsedit-commands" }
vsedit-events = { path = "../vsedit-events" }
vsedit-di = { path = "../vsedit-di" }
vsedit-languages = { path = "../vsedit-languages" }
vsedit-collections = { path = "../vsedit-collections" }
vsedit-diff = { path = "../vsedit-diff" }
vsedit-explorer = { path = "../vsedit-explorer" }
vsedit-glob = { path = "../vsedit-glob" }
vsedit-path = { path = "../vsedit-path" }
vsedit-ext-host = { path = "../vsedit-ext-host" }
vsedit-snippet = { path = "../vsedit-snippet" }
vsedit-suggest = { path = "../vsedit-suggest" }
vsedit-wb-search = { path = "../vsedit-wb-search" }
vsedit-workspace = { path = "../vsedit-workspace" }
vsedit-uri = { path = "../vsedit-uri" }
vsedit-configuration = { path = "../vsedit-configuration" }
vsedit-syntax = { path = "../vsedit-syntax" }
vsedit-workbench = { path = "../vsedit-workbench" }
vsedit-keybinding-svc = { path = "../vsedit-keybinding-svc" }
vsedit-keybindings = { path = "../vsedit-keybindings" }
vsedit-keycodes = { path = "../vsedit-keycodes" }
vsedit-contextkey = { path = "../vsedit-contextkey" }
vsedit-platform = { path = "../vsedit-platform" }
vsedit-editor-svc = { path = "../vsedit-editor-svc" }
vsedit-debug = { path = "../vsedit-debug" }
vsedit-folding = { path = "../vsedit-folding" }
vsedit-bracket = { path = "../vsedit-bracket" }
vsedit-merge-editor = { path = "../vsedit-merge-editor" }
vsedit-smartselect = { path = "../vsedit-smartselect" }
vsedit-stickyscroll = { path = "../vsedit-stickyscroll" }
vsedit-codelens = { path = "../vsedit-codelens" }
serde_json.workspace = true
tempfile.workspace = true
