[package]
name = "vsedit-ext-host"
description = "Extension host process management"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-ext-rpc = { path = "../vsedit-ext-rpc" }
vsedit-events = { path = "../vsedit-events" }
vsedit-uri = { path = "../vsedit-uri" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
dirs = { workspace = true }

[dev-dependencies]
tempfile = "3"

