[package]
name = "vsedit-editor-controller"
description = "Editor input controller"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-cursor = { path = "../vsedit-cursor" }
vsedit-editor-types = { path = "../vsedit-editor-types" }
vsedit-text-model = { path = "../vsedit-text-model" }
vsedit-viewmodel = { path = "../vsedit-viewmodel" }

