[package]
name = "vsedit-core"
description = "vsedit main binary"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-configuration = { path = "../vsedit-configuration" }
vsedit-di = { path = "../vsedit-di" }
vsedit-environment = { path = "../vsedit-environment" }
vsedit-ext-host = { path = "../vsedit-ext-host" }
vsedit-lifecycle-svc = { path = "../vsedit-lifecycle-svc" }
vsedit-log = { path = "../vsedit-log" }
vsedit-product = { path = "../vsedit-product" }
vsedit-tui = { path = "../vsedit-tui" }
vsedit-workbench = { path = "../vsedit-workbench" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

