[package]
name = "vsedit-files"
description = "Virtual file system service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-di = { path = "../vsedit-di" }
vsedit-events = { path = "../vsedit-events" }
vsedit-stream = { path = "../vsedit-stream" }
vsedit-uri = { path = "../vsedit-uri" }
notify = "7"
thiserror = { workspace = true }
tokio = { version = "1", features = ["fs", "sync"] }
tracing = { workspace = true }
walkdir = "2"

[dev-dependencies]
tempfile = "3"

