[package]
name = "vsedit-markers"
description = "Diagnostic markers service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-uri = { path = "../vsedit-uri" }
vsedit-events = { path = "../vsedit-events" }
vsedit-editor-types = { path = "../vsedit-editor-types" }

