[package]
name = "vsedit-workbench"
description = "Workbench shell assembly"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-commands = { path = "../vsedit-commands" }
vsedit-contextkey = { path = "../vsedit-contextkey" }
vsedit-editor-svc = { path = "../vsedit-editor-svc" }
vsedit-explorer = { path = "../vsedit-explorer" }
vsedit-input = { path = "../vsedit-input" }
vsedit-keybinding-svc = { path = "../vsedit-keybinding-svc" }
vsedit-keybindings = { path = "../vsedit-keybindings" }
vsedit-keycodes = { path = "../vsedit-keycodes" }
vsedit-notification = { path = "../vsedit-notification" }
vsedit-wb-layout = { path = "../vsedit-wb-layout" }
vsedit-wb-statusbar = { path = "../vsedit-wb-statusbar" }
vsedit-wb-textmate = { path = "../vsedit-wb-textmate" }
vsedit-wb-views = { path = "../vsedit-wb-views" }
vsedit-quickinput = { path = "../vsedit-quickinput" }
vsedit-terminal-view = { path = "../vsedit-terminal-view" }
vsedit-problems = { path = "../vsedit-problems" }
vsedit-output = { path = "../vsedit-output" }
vsedit-search-view = { path = "../vsedit-search-view" }
vsedit-scm-view = { path = "../vsedit-scm-view" }
vsedit-debug-view = { path = "../vsedit-debug-view" }
ratatui = { workspace = true }
walkdir = { workspace = true }

