[package]
name = "vsedit-async"
description = "Async utilities, throttle, debounce"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-cancellation = { path = "../vsedit-cancellation" }
vsedit-events = { path = "../vsedit-events" }
vsedit-lifecycle = { path = "../vsedit-lifecycle" }
futures = "0.3"
tokio = { version = "1", features = ["full"] }

