[package]
name = "vsedit-text-model"
description = "Text buffer using Ropey"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-collections = { path = "../vsedit-collections" }
vsedit-editor-types = { path = "../vsedit-editor-types" }
vsedit-events = { path = "../vsedit-events" }
vsedit-undoredo = { path = "../vsedit-undoredo" }
ropey = "1"
regex.workspace = true

