[package]
name = "vsedit-ipc"
description = "Inter-process communication"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vsedit-buffer = { path = "../vsedit-buffer" }
vsedit-di = { path = "../vsedit-di" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net", "io-util"] }

